spring.application.name=AIJobPortal

server.port=8082

spring.datasource.url=jdbc:h2:file:./data/aijobportal
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB